[project]
name = "cedar"
version = "0.2.0"
description = "Computational Environment for Dyanmics of Advanced Reactors"
requires-python = ">=3.13"
dependencies = [
    "matplotlib",
    "numpy",
    "meshio",
    "h5py",
    "CoolProp",
    "sphinx",
    "sphinx-rtd-theme",
    "pytest"
]

[build-system]
requires = ["setuptools>=80.9.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["cedar", "cedar.*"]
exclude = ["outputs", "examples"]